listofmsqlapp:
  - name: first-example-mysqlserver    
    os_type: Linux
    sku_name: P1v2
  - name: second-example-mysqlserver    
    os_type: Linux
    sku_name: EP1
  - name: third-example-mysqlserver    
    os_type: Linux
    sku_name: WS1
